---
title: "Batch Processing"
author: "Gaston Mauro Diaz"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Batch Processing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Bath processing

One of the main function of *caiman* package is *doOBIA*. It is used to get binarized images whit the aim of extract gap fraction and estimate forest structure or understory light transmission. After binarization you will need to continue the proccess with specific software as [CIMES]( http://jmnw.free.fr/).

This document shows you how to use a simple script for processing all the hemispherical photographs that are in an folder using doOBIA (batch processing).

If you are a frequently user of R probably you do not need to read this vignette.

## Script for batch processing

I assume that you take upward looking hemispherical photographs whit the optical axis aligned with the zenith (leveled). Also, I assume that the equipment gives you a circular picture inside the rectangular frame (i.e., is not a full-frame equipment) in JPEG format.

In the root of your *c* disk create a folder named *folder_in* and copy your photographs there. Also, create a folder named *folder_out*.

Run this code:
```
path_in <- "c:/folder_in" # Edit it if you need to (Do not use / at the end of the string)
path_out <- "c:/folder_out"

listofpics <- list.files(path_in, pattern = ".jpg", ignore.case = TRUE)

for (i in unique(listofpics)) {
  # see the help of loadPhoto with ?loadPhoto. 
  # Maybe you need to use the arguments upperLeft, width and height.
  x <- loadPhoto(paste0(path_in, "/", i))
  fisheye(x) <- newFishEye(TRUE, TRUE, FALSE)
  x <- normalize(x, 0, 255)
  # Here, I assume that your lens has perfect polor projection.
  z <- makeZimage(ncol(x), lensPolyCoef())
  # This takes a while but you can see the progres
  seg <- doPolarQtree(x, z, scaleParameter = 0.2)
  name <- strsplit(i, "\\.")[[1]][1]
  out <- doOBIA(x, z, seg, zlim = asAngle(c(20, 80)))
  writeRaster(out * 255, paste0(path_out, "/", name, ".TIF"), datatype = "INT1U", overwrite = TRUE)
}

```
Wait…
The result will be written in *c:/folder_out* whit the same name of the original photo.

